default:
  image: node:latest

stages:
  - lint
  - build-status

lint:
  stage: lint
  script: yarn run lint

build status:
  stage: build-status
  script:
    - yarn
    - yarn build
  cache:
    paths:
      - node_modules
      - .next/cache/
    key: ${CI_COMMIT_REF_SLUG}