default:
  image: node:latest

stages:
  - dependencies
  - buildstatus

dependencies:
  stage: dependencies
  script:
    - yarn
  cache:
    paths:
      - node_modules

buildstatus:
  stage: buildstatus
  script: yarn run build || exit 1
  only:
    - success
  except:
    - failed