default:
  image: node:latest

cache:
  paths:
    - node_modules

stages:
  - lint
  - build-status

before_script:
  - yarn

lint:
  stage: lint
  script:
    - yarn lint

build status:
  stage: build-status

  script:
    - yarn build
  cache:
    paths:
      - .next/cache/
    key: ${CI_COMMIT_REF_SLUG}
