default:
  image: node:latest

stages: 
  - dependencies
  - build-status
  - lint

deps:
  stage: dependencies
  script:
    - yarn
  cache:
    paths:
      - node_modules

build status:
  stage: build-status
  needs: [deps]
  
  script:
    - yarn build
  cache:
    paths:
      - .next/cache/
    key: ${CI_COMMIT_REF_SLUG}

lint:
  stage: lint
  needs: [deps, build status]
  script: yarn run lint