default:
  image: node:latest

cache:
  paths:
    - node_modules
    - .yarn

stages:
  - lint
  - build-status

before_script:
  - yarn config set cache-folder "$(pwd)/.yarn"
  - yarn install --cache-folder "$(pwd)/.yarn"
  - cd email
  - yarn install --cache-folder "$(pwd)/.yarn"

lint:
  stage: lint
  script:
    - yarn lint

build status:
  stage: build-status

  script:
    - yarn build
  cache:
    paths:
      - .next/cache/
    key: ${CI_COMMIT_REF_SLUG}
