-- CreateEnum
CREATE TYPE "APIKeyPermission" AS ENUM ('USER_PROFILE_READ', 'USER_PROFILE_WRITE', 'USER_GAMES_READ', 'USER_GAMES_WRITE', 'GATEWAY', 'USER_MEDIA_READ', 'USER_CHAT_READ', 'USER_CHAT_WRITE', 'USER_CHECKLIST_READ', 'USER_CHECKLIST_WRITE');

-- CreateTable
CREATE TABLE "APIKey" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "permissions" "APIKeyPermission"[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "APIKey_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "APIKey_key_key" ON "APIKey"("key");

-- AddForeignKey
ALTER TABLE "APIKey" ADD CONSTRAINT "APIKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
